name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: [ '2.2.103', '3.1.101' ]
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Build and test
      run: |
        git submodule update --init
        npm ci
        npm test
